spring.application.name=bankProject
spring.datasource.url=jdbc:postgresql://localhost:5433/bankDB
spring.datasource.username=postgres
spring.datasource.password=ilovedjango#
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
